# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Macos-cli-test:
    name: MacOS CLI Test
    runs-on: macos-latest
    outputs:
      status: ${{ steps.status-mark.outputs.status }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - spark: 3.1.1
            java: 8
            hadoop: 3.2
            spark-major: "3.0"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: status-mark
        if: ${{ always() }}
        run: echo "::set-output name=status::$(${{job.status}})"

  report:
    name: Test result report
    if: ${{ always() }}
    needs: [ Macos-cli-test ]
    runs-on: ubuntu-latest
    steps:
      - name: Report
        run: echo ${{needs.Macos-cli-test.outputs.status}}
